# Use a modern Docker Compose file format
# version: '3.8'

services:
  # Define your web service
  web:
    # Build the image using the Dockerfile in the current directory
    build: .
    # Map port 4001 on the host to port 4001 in the container
    ports:
      - "4001:4001"
    # Mount a named volume to persist the downloaded GloVe data
    # The volume is mounted to the '/app/glove' directory inside the container
    # where the application expects the GloVe file to be.
    volumes:
      - glove_data:/app/glove
    # Restart the container if it exits, unless stopped manually
    restart: unless-stopped
    # Environment variables for production mode
    environment:
      - FLASK_ENV=production
    # If you need different configurations for different environments, 
    # you can use profiles or create separate compose files

# For development mode, you can create a docker-compose.dev.yml file
# or use profiles, or run with the override below:
# 
# To run in development mode:
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
# 
# Where docker-compose.dev.yml would contain:
# services:
#   web:
#     environment:
#       - FLASK_ENV=development

# Define the named volume
volumes:
  # This creates a volume managed by Docker to store the glove data persistently
  glove_data: