# https://taskfile.dev

version: '3'

tasks:

  up_dev:
    aliases:
      - up
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d

  up_build:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build

  down:
    cmds:
      - docker compose down

  up_prod:
    cmds:
      - docker compose up -d

  up_build_prod:
    cmds:
      - docker compose up -d --build



